//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Decision_Maker.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Decision_Maker.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About app.
        /// </summary>
        internal static string About_app {
            get {
                return ResourceManager.GetString("About app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a title to your decision.
        /// </summary>
        internal static string Add_a_title_to_your_decision {
            get {
                return ResourceManager.GetString("Add a title to your decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Criteria.
        /// </summary>
        internal static string Add_Criteria {
            get {
                return ResourceManager.GetString("Add Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Criterion.
        /// </summary>
        internal static string Add_Criterion {
            get {
                return ResourceManager.GetString("Add Criterion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add up to 5 criteria.
        /// </summary>
        internal static string Add_up_to_5_criteria {
            get {
                return ResourceManager.GetString("Add up to 5 criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account? .
        /// </summary>
        internal static string Already_have_an_account {
            get {
                return ResourceManager.GetString("Already have an account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Decision.
        /// </summary>
        internal static string Create_a_Decision {
            get {
                return ResourceManager.GetString("Create a Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a decision, add options and criteria, then compare them step by step. Get a clear winner and see why it ranked highest..
        /// </summary>
        internal static string Create_a_decision_add_options_and_criteria {
            get {
                return ResourceManager.GetString("Create a decision add options and criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Maker.
        /// </summary>
        internal static string Decision_Maker {
            get {
                return ResourceManager.GetString("Decision Maker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account? .
        /// </summary>
        internal static string Dont_have_an_account {
            get {
                return ResourceManager.GetString("Dont have an account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email.
        /// </summary>
        internal static string Enter_email {
            get {
                return ResourceManager.GetString("Enter email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name.
        /// </summary>
        internal static string Enter_name {
            get {
                return ResourceManager.GetString("Enter name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        internal static string Enter_password {
            get {
                return ResourceManager.GetString("Enter password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: Choose a car.
        /// </summary>
        internal static string Example_Choose_a_car {
            get {
                return ResourceManager.GetString("Example Choose a car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: Price.
        /// </summary>
        internal static string Example_Price {
            get {
                return ResourceManager.GetString("Example Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string Forgot_password {
            get {
                return ResourceManager.GetString("Forgot password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guest.
        /// </summary>
        internal static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string Log_in {
            get {
                return ResourceManager.GetString("Log in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string Log_out {
            get {
                return ResourceManager.GetString("Log out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New decision.
        /// </summary>
        internal static string New_decision {
            get {
                return ResourceManager.GetString("New decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in.
        /// </summary>
        internal static string Not_logged_in {
            get {
                return ResourceManager.GetString("Not logged in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in first. Redirecting to home..
        /// </summary>
        internal static string Please_log_in_first {
            get {
                return ResourceManager.GetString("Please log in first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        internal static string Repeat_password {
            get {
                return ResourceManager.GetString("Repeat password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results .
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start as guest.
        /// </summary>
        internal static string Start_as_guest {
            get {
                return ResourceManager.GetString("Start as guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, {0}!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well-founded decision = calmer mind.
        /// </summary>
        internal static string Well_founded_decision {
            get {
                return ResourceManager.GetString("Well founded decision", resourceCulture);
            }
        }
    }
}
